# Config file for MinecraftPlugin

WelcomeMessage: '&5Welcome to the server!'
NotPlayerMessage: '&CYou must be a player to use this command!'
NoPermissionMessage: '&CYou do not have the right permissions to do that!'
  